api: true

log:
    level: INFO

global:
    sendAnonymousUsage: true

providers:
    file:
        directory: /etc/traefik
    docker:
        exposedbydefault: false

entryPoints:
    web:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: websecure
    websecure:
        address: ":443"
        http:
            middleware:
            tls:
                certResolver: szynalcoukchallenge

certificatesresolvers:
    szynalcoukchallenge:
        acme:
            httpChallenge:
                entryPoint: web
            email: robert@szynal.co.uk
            storage: /etc/traefik/letsencrypt/szynal.co.uk.json

