#!/bin/sh

adapter_name='WiFi'
gp_adapter_name='GlobalProtect'
powershell_bin='/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/powershell.exe'
powershell_cmd="\$netAdapter = If ( get-netadapter -Name '${gp_adapter_name}' | Where-Object {\$_.Status -eq 'Up'} ) { '${gp_adapter_name}' } else { '${adapter_name}' }; Get-DnsClientServerAddress -InterfaceAlias \"\$netAdapter\" -AddressFamily IPv4 | Select -ExpandProperty ServerAddresses"
file_name=$(basename ${0})

if [ "$(pgrep ${file_name} | grep -v ^$ | wc -l)" -gt 2 ] 
then
	if [ -n "${1}" ]; then echo 'DEBUG: Already running'; fi
	exit 0
fi

while true
do
	if [ -n "${1}" ]; then echo 'DEBUG: Generating config'; fi
	timeout 40 ${powershell_bin} -Command ${powershell_cmd} | \
		head -n2 | \
		awk -v script_path=${0} 'BEGIN { timestamp = strftime("%F %T"); print "# Generated by " script_path " on " timestamp; print } { print "nameserver", $1 }' | \
		tr -d '\r' > /tmp/resolv.conf && \
	grep -q nameserver /tmp/resolv.conf && \
	cp /tmp/resolv.conf /etc/resolv.conf
	if [ -n "${1}" ]; then echo 'DEBUG: Sleeping'; fi
	sleep 58
done

