#!/bin/sh

adapter_name='WiFi'
powershell_bin='/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/powershell.exe'
powershell_cmd="get-netadapter -name \"${adapter_name}\" | Get-DnsClientServerAddress | Select -ExpandProperty ServerAddresses"
file_name=$(basename ${0})

if [ "$(pgrep ${file_name} | grep -v ^$ | wc -l)" -gt 2 ] 
then
	if [ -n "${1}" ]; then echo 'DEBUG: Already running'; fi
	exit 0
fi

while true
do
	if [ -n "${1}" ]; then echo 'DEBUG: Generating config'; fi
	timeout 40 ${powershell_bin} -Command ${powershell_cmd} | \
		awk -v script_path=${0} 'BEGIN { print "# Generated by " script_path; print } { print "nameserver", $1 }' | \
		tr -d '\r' > /tmp/resolv.conf && \
	grep -q nameserver /tmp/resolv.conf && \
	cp /tmp/resolv.conf /etc/resolv.conf
	if [ -n "${1}" ]; then echo 'DEBUG: Sleeping'; fi
	sleep 58
done

